/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Training API
 * API for training management
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type Get200 = {
  message: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  id: string;
  name: string;
  order: number;
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItemSessionsItem = {
  id: string;
  workoutDayId: string;
  startedAt: string;
  completedAt?: string;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  id: string;
  name: string;
  weekDay: string;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
  sessions: ListWorkoutPlans200ItemWorkoutDaysItemSessionsItem[];
};

export type ListWorkoutPlans200Item = {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItem = {
  id: string;
  weekDay: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200ExercisesItem = {
  id: string;
  name: string;
  order: number;
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDay200SessionsItem = {
  id: string;
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  weekDay: string;
  exercises: GetWorkoutDay200ExercisesItem[];
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
};

export type CompleteWorkoutSession401 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession404 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession409 = {
  error: string;
  code: string;
};

export type CompleteWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetHome200TodayWorkoutDayWeekDay =
  (typeof GetHome200TodayWorkoutDayWeekDay)[keyof typeof GetHome200TodayWorkoutDayWeekDay];

export const GetHome200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHome200TodayWorkoutDay = {
  workoutPlanId: string;
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHome200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHome200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHome200 = {
  activeWorkoutPlanId: string;
  todayWorkoutDay: GetHome200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHome200ConsistencyByDay;
};

export type GetHome401 = {
  error: string;
  code: string;
};

export type GetHome404 = {
  error: string;
  code: string;
};

export type GetHome500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats404 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetMe200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

/**
 * Hello World
 */
export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[];
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans?${stringifiedParams}`
    : `/workout-plans`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get a workout plan
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError;

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const getWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(
    getGetWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get a workout day
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError;

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Complete a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200;
  status: 200;
};

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401;
  status: 401;
};

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404;
  status: 404;
};

export type completeWorkoutSessionResponse409 = {
  data: CompleteWorkoutSession409;
  status: 409;
};

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500;
  status: 500;
};

export type completeWorkoutSessionResponseSuccess =
  completeWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type completeWorkoutSessionResponseError = (
  | completeWorkoutSessionResponse401
  | completeWorkoutSessionResponse404
  | completeWorkoutSessionResponse409
  | completeWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type completeWorkoutSessionResponse =
  | completeWorkoutSessionResponseSuccess
  | completeWorkoutSessionResponseError;

export const getCompleteWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const completeWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  completeWorkoutSessionBody: CompleteWorkoutSessionBody,
  options?: RequestInit,
): Promise<completeWorkoutSessionResponse> => {
  return customFetch<completeWorkoutSessionResponse>(
    getCompleteWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(completeWorkoutSessionBody),
    },
  );
};

/**
 * @summary Get home page data
 */
export type getHomeResponse200 = {
  data: GetHome200;
  status: 200;
};

export type getHomeResponse401 = {
  data: GetHome401;
  status: 401;
};

export type getHomeResponse404 = {
  data: GetHome404;
  status: 404;
};

export type getHomeResponse500 = {
  data: GetHome500;
  status: 500;
};

export type getHomeResponseSuccess = getHomeResponse200 & {
  headers: Headers;
};
export type getHomeResponseError = (
  | getHomeResponse401
  | getHomeResponse404
  | getHomeResponse500
) & {
  headers: Headers;
};

export type getHomeResponse = getHomeResponseSuccess | getHomeResponseError;

export const getGetHomeUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHome = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeResponse> => {
  return customFetch<getHomeResponse>(getGetHomeUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse404 = {
  data: GetStats404;
  status: 404;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse404
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats?${stringifiedParams}`
    : `/stats`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get current user train data
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/me`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse200 = {
  data: void;
  status: 200;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponse = postAiResponseSuccess;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
  });
};
